# Default Spark cluster manager
# All spark-submit commands will connect to this Spark Master
spark.master                           spark://spark-master:7077

# Enable Spark event logging
# Required for Spark History Server to work
spark.eventLog.enabled                 true

# Directory where Spark writes execution event logs
# This path is shared via a Docker volume
spark.eventLog.dir                     /opt/spark/spark-events

# Directory from which the History Server reads event logs
# Must match spark.eventLog.dir
spark.history.fs.logDirectory          /opt/spark/spark-events